version: '3.1'
services:
  education-course:
    container_name: dev-youcai-admin-server
    restart: always
    image: dev/youcai-admin:v1.0.0
    network_mode: "host"
    volumes:
      - /opt/youcai-admin-server/logs:/youcai-admin/logs
    command: java -jar -Xms1024m -Xmx1024m -Duser.timezone=GMT+08 youcai-admin-1.0.0-SNAPSHOT.jar --spring.profiles.active=dev
